# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build-dev
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install vuejs cli  
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: global add @vue/cli@latest
      
#       - name: Run yarn install
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: install
        
#       - run: mv src/statics/chain-manifests-dev.json src/statics/chain-manifests.json
#       - run: mv src/statics/app-manifest-dev.json src/statics/app-manifest.json
        
#       - name: Run Build  
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: build
#         env:
#           APP_NAME: '"DAO Kit"'
#           NETWORK_HOST: '"testnet.telos.caleos.io"'
#           NETWORK_PROTOCOL: '"https"'
#           NETWORK_PORT: '443'
#           DAO_CONTRACT: '"mygenericdao"'
#           ACCOUNT_API_URL: '"https://opqeierg9e.execute-api.us-east-1.amazonaws.com/dev"'
#           BLOCKCHAIN_EXPLORER: '"https://telos-test.bloks.io"'
#           PPP_ENV: '"test"'
#           SENTRY_DSN: '""'
#           DOCUMENTATION: '"https://notepad.diglife.coop/6w_69K_8QLSbzNaYcDWtHw?view "'
          
          
#       - name: Upload the build
#         uses: actions/upload-artifact@v1
#         with:
#           name: dist
#           path: dist/*
          
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download the build
#         uses: actions/download-artifact@v1
#         with:
#           name: dist
#       - name: S3 Sync 
#       - uses: actions/checkout@master
#       - uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --follow-symlinks
#         env:
#           AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
#           SOURCE_DIR: 'dist'      # optional: defaults to entire repository
         
 
