# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: node-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
          APP_NAME: '"DAO Kit"'
          NETWORK_HOST: '"testnet.telos.caleos.io"'
          NETWORK_PROTOCOL: '"https"'
          NETWORK_PORT: '443'
          DAO_CONTRACT: '"mygenericdao"'
          ACCOUNT_API_URL: '"https://opqeierg9e.execute-api.us-east-1.amazonaws.com/dev"'
          BLOCKCHAIN_EXPLORER: '"https://telos-test.bloks.io"'
          PPP_ENV: '"test"'
          SENTRY_DSN: '""'
          DOCUMENTATION: '"https://notepad.diglife.coop/6w_69K_8QLSbzNaYcDWtHw?view "'
      - name: build
        run: 
          yarn global add @vue/cli@latest
          yarn install
          mv src/statics/chain-manifests-dev.json src/statics/chain-manifests.json
          mv src/statics/app-manifest-dev.json src/statics/app-manifest.json
          yarn build
#       - name: Upload the build
#         uses: actions/upload-artifact@v1
#         with:
#           name: dist
#           path: dist/*
          
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download the build
#         uses: actions/download-artifact@v1
#         with:
#           name: dist
#       - name: S3 Sync 
#       - uses: actions/checkout@master
#       - uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --follow-symlinks
#         env:
#           AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
#           SOURCE_DIR: 'dist'      # optional: defaults to entire repository
         
 
