name: Build and Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn global add @vue/cli@latest
      - run: yarn install
      - run: mv src/statics/chain-manifests-prod.json src/statics/chain-manifests.json
      - run: mv src/statics/app-manifest-prod.json src/statics/app-manifest.json
      - run: yarn build
        env:
          APP_NAME: '"GBA DAO"'
          NETWORK_CHAIN_ID: '"4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11"'
          NETWORK_HOST: '"telos.caleos.io"'
          NETWORK_PROTOCOL: '"https"'
          NETWORK_PORT: '443'
          DAO_CONTRACT: '"dao.gba"'
          ACCOUNT_API_URL: '"https://tb3nnn0qa9.execute-api.us-east-1.amazonaws.com/prod"'
          BLOCKCHAIN_EXPLORER: '"https://telos.bloks.io"'
          PPP_ENV: '"prod"'
          SENTRY_DSN: '"https://319dc652abba4ba59d6688a37d02eaf1@o302102.ingest.sentry.io/5220899"'
          DOCUMENTATION: '"https://notepad.diglife.coop/6w_69K_8QLSbzNaYcDWtHw?view "'


      - name: S3 Sync and Invalidate Cloudfront Distribution
        uses: digital-scarcity/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist'      # optional: defaults to entire repository
          AWS_DISTRIBUTION_ID: ${{ secrets.PROD_DISTRIBUTION_ID }}
